name: Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.4, 8.0, 8.1, 8.2, 8.3, 8.4 ]
        laravel: [ ^6.0, ^7.0, ^8.0, ^9.0, ^10.0, ^11.0, ^12.0 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: ^6.0
            testbench: ^4.9.1
          - laravel: ^7.0
            testbench: ^5.9.1
          - laravel: ^8.0
            testbench: ^6.6.1
          - laravel: ^9.0
            testbench: ^7.0
          - laravel: ^9.0
            testbench: ^7.0
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
          - laravel: ^12.0
            testbench: ^10.0
        exclude:
          - laravel: '^6.0'
            php: '8.0'
          - laravel: '^6.0'
            php: '8.1'
          - laravel: '^6.0'
            php: '8.2'
          - laravel: '^6.0'
            php: '8.3'
          - laravel: '^6.0'
            php: '8.4'
          - laravel: '^7.0'
            php: '8.0'
          - laravel: '^7.0'
            php: '8.1'
          - laravel: '^7.0'
            php: '8.2'
          - laravel: '^7.0'
            php: '8.3'
          - laravel: '^7.0'
            php: '8.4'
          - laravel: '^8.0'
            php: '8.2'
          - laravel: '^8.0'
            php: '8.3'
          - laravel: '^8.0'
            php: '8.4'
          - laravel: '^9.0'
            php: '7.4'
          - laravel: '^9.0'
            php: '8.4'
          - laravel: '^9.0'
            php: '8.3'
          - laravel: '^10.0'
            php: '7.4'
          - laravel: '^10.0'
            php: '8.0'
          - laravel: '^11.0'
            php: '7.4'
          - laravel: '^11.0'
            php: '8.0'
          - laravel: '^11.0'
            php: '8.1'
          - laravel: '^12.0'
            php: '7.4'
          - laravel: '^12.0'
            php: '8.0'
          - laravel: '^12.0'
            php: '8.1'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install minimum required Mockery version on PHP 8 with prefer lowest stability
        if: |
          matrix.php == '8.0' &&
          matrix.stability == 'prefer-lowest' &&
          (matrix.laravel == '^6.0' || matrix.laravel == '^7.0' || matrix.laravel == '^7.0')
        run: |
          composer require "mockery/mockery:^1.4.2" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install minimum required packages on PHP 8.1 with prefer lowest stability
        if: ${{ matrix.php == '8.1' && matrix.stability == 'prefer-lowest' && matrix.laravel == '^8.0' }}
        run: |
          composer require "laravel/framework:^8.62.0" --no-interaction --no-update
          composer require "laravel/legacy-factories:^1.1.1" --no-interaction --no-update
          composer require "nesbot/carbon:^2.51.0" --no-interaction --no-update
          composer require "symfony/http-foundation:^5.3.7" --no-interaction --no-update
          composer require "symfony/console:^5.3.7" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install minimum required packages on PHP 8.2 with prefer lowest stability
        if: ${{ matrix.php == '8.2' && matrix.stability == 'prefer-lowest' && matrix.laravel == '^9.0' }}
        run: |
          composer require "nesbot/carbon:^2.62.1" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install minimum required packages on PHP 8.1 with prefer lowest stability
        if: ${{ matrix.php == '8.1' && matrix.stability == 'prefer-lowest' && matrix.laravel == '^8.0' }}
        run: |
          composer require "laravel/framework:^8.62.0" --no-interaction --no-update
          composer require "laravel/legacy-factories:^1.1.1" --no-interaction --no-update
          composer require "nesbot/carbon:^2.51.0" --no-interaction --no-update
          composer require "symfony/http-foundation:^5.3.7" --no-interaction --no-update
          composer require "symfony/console:^5.3.7" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Custom PHPUnit config for new versions
        if: ${{ (matrix.php == '8.2' && matrix.laravel == '^11.0')
          || (matrix.php == '8.2' && matrix.laravel == '^12.0')
          || (matrix.php == '8.3' && matrix.laravel == '^12.0')
          || (matrix.php == '8.3' && matrix.stability == 'prefer-stable' && matrix.laravel == '^11.0')
          || (matrix.php == '8.4' && matrix.stability == 'prefer-stable' && matrix.laravel == '^11.0')
          || (matrix.php == '8.4' && matrix.laravel == '^12.0') }}
        run: cp phpunit.11.xml.dist phpunit.xml.dist

      - name: Execute tests
        run: composer run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/clover.xml
